---
- name: Transform rpi 
  hosts: localhost 
  connection: local
  gather_facts: no
  become: true

  tasks:

  - name: Install dependencies
    apt: 
      name: "{{ packages }}"
    vars:
      packages:
        - screen
        - ethtool
        - curl
        - python3-pygame
        - python3-requests
        - python3-pip
        - ifplugd
        - lldpd
        - python3-flask
        - python3-yaml
        - uwsgi-plugin-python3
        - uwsgi
        - python3-scapy

  - name: install pyroute2
    pip:
      name: git+https://github.com/svinota/pyroute2.git
      version: 0.5.3
      executable: pip3

  - name: create pi .ssh dir
    file:
      path: "/home/pi/.ssh"
      state: directory

  - name: copy pub ssh key
    template: 
      src: templates/id_rsa.pub
      dest: /home/pi/.ssh/authorized_keys
      owner: pi
      group: pi 
      mode: '0600'

  - name: Create namespace
    ip_netns:
      name: dp
      state: present
    register: ns_setup

  - name: place eth0 into dp netns
    shell: ip link set dev eth0 netns dp
    when: ns_setup['changed'] == True 

  - name: copy ifplugd templates
    template:
      src: templates/ifplugd/ifupdown
      dest: /etc/ifplugd/action.d/ifupdown
      owner: root
      group: root
      mode: '0755'
      backup: yes
    register: ifplugd_config_changed

  - name: Check status of ifplugd inside namespace
    shell: ip netns exec dp ifplugd -c
    register: ifplugd_not_running
    changed_when: "'ifplugd not running' in ifplugd_not_running.stdout"
    failed_when: (ifplugd_not_running.rc != 255) and (ifplugd_not_running.rc != 0) 

  - name: Start ifplugd inside namespace
    shell: nohup ip netns exec dp ifplugd -I -i eth0 &
    when: ifplugd_not_running['changed'] == True 

  - name: debug stuff
    debug:
      var: ns_setup
